version: '3'

includes:
  utopia: ./taskfiles/utopia.yaml
  build: ./taskfiles/build.yaml
  format: ./taskfiles/format.yaml

tasks:
  default:
    - task -a

  setup:
    cmds:
      - curl https://get.volta.sh | bash
      - volta install node
      - volta install pnpm

  install:
    source: package.json
    generates:
      - pnpm-lock.yaml
    cmds:
      - echo "Installing package.json deps"
      - pnpm install

  build:
    deps: [clean, install]
    cmds:
      - task build:default

  build:watch:
    deps: [install, utopia, format:src, build:default]
    watch: true

  serve:
    cmds:
      - pnpm live-server --open=dist

  clean:
    cmds:
      - rm -rf ./dist
      - mkdir ./dist
