version: '3'

includes:
  format: ./format.yaml
  assets: ./assets.yaml
  setup: ./setup.yaml
    
tasks:
  default:
    deps:
      - task: setup:install
      - task: setup:clean
      - task: assets:create
      - task: format:src
    sources:
      - src/_includes/**/*.{njk}
      - src/css/**/*.css
      - src/design-tokens/**/*.json
    generates:
      - dist/index.html
      - dist/css/global.css
    cmds:
      - pnpm eleventy
      - pnpm postcss src/css/global.css -o dist/css/global.css
      - task: format:dist

  deploy:
    deps: [build]
    cmds:
      - pnpm gh-pages -d dist -b deploy
