version: '3'

includes:
  assets: ./assets.yaml
  setup: ./setup.yaml
    
tasks:
  default:
    env:
      NODE_ENV: ""
    deps:
      - task: clean
      - task: setup:install
    sources:
      - src/_includes/**/*.{njk}
      - src/css/**/*.css
      - src/design-tokens/**/*.json
    generates:
      - dist/index.html
      - dist/css/global.css
    cmds:
      - echo {{.NODE_ENV}}
      - task: assets:create
      - pnpm eleventy
      - pnpm postcss src/css/global.css -o dist/css/global.css

  deploy:
    cmds:
      - task: default
      - pnpm gh-pages -d dist -b deploy
      
  clean:
    cmds:
      - rm -rf ./dist
      - mkdir ./dist
