version: '3'

includes:
  assets: ./assets.yaml
  format: ./format.yaml

tasks:
  default:
    cmds:
      - task build:site
      - task format:dist

  site:
    deps: [assets]
    sources:
      - src/_includes/**/*.{njk}
      - src/css/**/*.css
      - src/design-tokens/**/*.json
    generates:
      - dist/index.html
      - dist/css/global.css
    cmds:
      - pnpm eleventy
      - task build:postcss

  postcss:
    cmds:
      - pnpm postcss src/css/global.css -o dist/css/global.css
