name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run Taskfile - build
        run: task build:deploy
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Update About Section
        if: ${{ success() }}
        env:
          REPO: ${{ github.repository }}
        run: |
          gh api \
            -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -F "description=$(jq -r '.summary' utils/project.json)" \
            -F "homepage=https://ortiz-antonio.github.io/$(jq -r '.key' utils/project.json)" \
            /repos/"$REPO"
